site_name: FIWARE Augmented Reality
site_url: https://fiware-augmentedreality.readthedocs.org
repo_url: https://github.com/stlemme/fiware-augmentedreality.git
site_description: Augmented Reality - Documentation
google_analytics: ['UA-84207637-2', 'fiware-augmentedreality.readthedocs.io']
docs_dir: docs
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  - Home: index.md  
  - 'User & Programmers Manual': 'user_guide.md'      
  - 'Installation & Administration Manual': 'installation_guide.md'
      